### ISSUE TITLE
0.0.7 can not build on ubuntu 14.04

### ISSUE THREAD

**Issue by randoms** [RobotWebTools/web_video_server#47]
error messages
```
/home/xiaoqiang/Documents/ros/src/web_video_server/src/libav_streamer.cpp: In destructor ‘web_video_server::LibavStreamer::~LibavStreamer()’:
/home/xiaoqiang/Documents/ros/src/web_video_server/src/libav_streamer.cpp:75:26: error: ‘av_frame_free’ was not declared in this scope
     av_frame_free(&frame_);
                          ^
/home/xiaoqiang/Documents/ros/src/web_video_server/src/libav_streamer.cpp: In member function ‘virtual void web_video_server::LibavStreamer::initialize(const cv::Mat&)’:
/home/xiaoqiang/Documents/ros/src/web_video_server/src/libav_streamer.cpp:166:27: error: ‘av_frame_alloc’ was not declared in this scope
   frame_ = av_frame_alloc();
                           ^
/home/xiaoqiang/Documents/ros/src/web_video_server/src/libav_streamer.cpp: In member function ‘virtual void web_video_server::LibavStreamer::sendImage(const cv::Mat&, const ros::Time&)’:
/home/xiaoqiang/Documents/ros/src/web_video_server/src/libav_streamer.cpp:227:39: error: ‘av_frame_alloc’ was not declared in this scope
   AVFrame *raw_frame = av_frame_alloc();
                                       ^
/home/xiaoqiang/Documents/ros/src/web_video_server/src/libav_streamer.cpp:229:87: error: ‘av_image_fill_arrays’ was not declared in this scope
               img.data, input_coding_format, output_width_, output_height_, 0);
                                                                              ^
/home/xiaoqiang/Documents/ros/src/web_video_server/src/libav_streamer.cpp:248:27: error: ‘av_frame_free’ was not declared in this scope
   av_frame_free(&raw_frame);
                           ^
/home/xiaoqiang/Documents/ros/src/web_video_server/src/libav_streamer.cpp:319:23: error: ‘av_packet_unref’ was not declared in this scope
   av_packet_unref(&pkt);
                       ^
make[2]: *** [web_video_server/CMakeFiles/web_video_server.dir/src/libav_streamer.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [web_video_server/CMakeFiles/web_video_server.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j4 -l4" failed

```
